### ISSUE TITLE
Any chance for service account support?

### ISSUE THREAD

**Issue by pmjohann** [jupemara/spreadsheet-sql#17]
Hi there,

I find your package great, the only thing I'm missing is service account support.
Any chances you plan on supporting them in the near future?

Thank you!

**Comment by jupemara** [comment]
Hi pmjohann,

We have no plan to support other authentication method except oauth2 for now (next 1 or 2 weeks).
However actually I feel the thing same with your opinion on occasion LOL.

So I decided to be going to implement to use another authentication methods.

Thanks, too.

**Comment by jupemara** [comment]
https://github.com/jupemara/spreadsheet-sql/pull/36

**Comment by jupemara** [comment]
In #36 PR you can pass `AuthClient` of `google-api-nodejs-client` as `PrivateSheet`'s argument.
It means now you can use gcp service account, OAuth2 etc.
Please check https://github.com/jupemara/spreadsheet-sql/blob/master/test/e2e/GCPServiceAccount.ts . Or to use service account as gcp default credential method.

```javascript
const PrivateSpreadSheet = require('./lib/PrivateSpreadsheet').PrivateSpreadsheet;
const GoogleAuth = require('google-auth-library').GoogleAuth;

(async () => {
  const client = new GoogleAuth({
    scopes: 'https://www.googleapis.com/auth/spreadsheets',
  });
  const sheet = new PrivateSpreadSheet(
    'SPREADSHEET_KEY',
    'WORKSHEET_NAME',
    client,
  );
  const data = await sheet.query(
    'SELECT * WHERE A = "user001"',
  );
  console.log(data);
})();
```
